### ISSUE TITLE
MATE Terminal segfaults and crashes when changing keyboard shortcut.

### ISSUE THREAD

**Issue by tidux** [mate-desktop/mate-terminal#228]
#### Expected behaviour
Keyboard shortcut is changed, mate-terminal does not crash.

#### Actual behaviour
Keyboard shortcut is changed, mate-terminal crashes.  The following error appears in dmesg:
` mate-terminal[5327] general protection ip:7fb97d8c35c7 sp:7ffd42656f50 error:0 in libgtk-3.so.0.2200.27[7fb97d534000+707000]`

#### Steps to reproduce the behaviour
Change any keyboard shortcut in mate-terminal's settings menu.

#### MATE general version
1.20

#### Package version
1.20

#### Linux Distribution
Arch Linux

#### Link to downstream report of your Distribution
n/a - upstream problem

**Comment by alexarnaud** [comment]
Le 15/02/2018 à 08:15, Tidux a écrit :
>         Linux Distribution

What is your Linux distribution ?

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by alexarnaud** [comment]
Le 15/02/2018 à 09:04, Alex ARNAUD a écrit :
> Le 15/02/2018 à 08:15, Tidux a écrit :
>  > Linux Distribution
> 
> What is your Linux distribution ?

I can't reproduce the issue you describe with Mate Terminal 1.20 on 
Debian Sid.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-terminal/issues/197

**Comment by monsta** [comment]
Hmm, doesn't look like the offscreen patch from Ubuntu had been upstreamed yet. Might be some other crash.

**Comment by monsta** [comment]
Please post the backtrace from the crash.

https://wiki.archlinux.org/index.php/Core_dump#Examining_a_core_dump

**Comment by tidux** [comment]
```
       Message: Process 22683 (mate-terminal) of user 1000 dumped core.
                
                Stack trace of thread 22683:
                #0  0x00007f61cf0fe5c7 gtk_widget_get_toplevel (libgtk-3.so.0)
                #1  0x00007f61cf120593 n/a (libgtk-3.so.0)
                #2  0x00007f61cf120903 gtk_window_group_add_window (libgtk-3.so.0)
                #3  0x00007f61cf11d378 gtk_window_set_transient_for (libgtk-3.so.0)
                #4  0x00007f61cf0b5793 n/a (libgtk-3.so.0)
                #5  0x00007f61cf0b6678 n/a (libgtk-3.so.0)
                #6  0x00007f61cefa4cfe gtk_main_do_event (libgtk-3.so.0)
                #7  0x00007f61ceaad9f6 n/a (libgdk-3.so.0)
                #8  0x00007f61ceae0225 n/a (libgdk-3.so.0)
                #9  0x00007f61cd5e4e38 g_main_context_dispatch (libglib-2.0.so.0)
                #10 0x00007f61cd5e5081 n/a (libglib-2.0.so.0)
                #11 0x00007f61cd5e53b2 g_main_loop_run (libglib-2.0.so.0)
                #12 0x00007f61cefa3eff gtk_main (libgtk-3.so.0)
                #13 0x00005577506682c5 n/a (mate-terminal)
                #14 0x00007f61cca9ef4a __libc_start_main (libc.so.6)
                #15 0x00005577506683aa n/a (mate-terminal)
                
                Stack trace of thread 22686:
                #0  0x00007f61ccb6997b __poll (libc.so.6)
                #1  0x00007f61cd5e4ff3 n/a (libglib-2.0.so.0)
                #2  0x00007f61cd5e510e g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f61cd5e5162 n/a (libglib-2.0.so.0)
                #4  0x00007f61cd60d26a n/a (libglib-2.0.so.0)
                #5  0x00007f61cce3c08c start_thread (libpthread.so.0)
                #6  0x00007f61ccb73e7f __clone (libc.so.6)
                
                Stack trace of thread 22687:
                #0  0x00007f61ccb6997b __poll (libc.so.6)
                #1  0x00007f61cd5e4ff3 n/a (libglib-2.0.so.0)
                #2  0x00007f61cd5e53b2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f61cdbd96d8 n/a (libgio-2.0.so.0)
                #4  0x00007f61cd60d26a n/a (libglib-2.0.so.0)
                #5  0x00007f61cce3c08c start_thread (libpthread.so.0)
                #6  0x00007f61ccb73e7f __clone (libc.so.6)
                
                Stack trace of thread 22689:
                #0  0x00007f61ccb6997b __poll (libc.so.6)
                #1  0x00007f61cd5e4ff3 n/a (libglib-2.0.so.0)
                #2  0x00007f61cd5e510e g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f61c0db8b0e n/a (libdconfsettings.so)
                #4  0x00007f61cd60d26a n/a (libglib-2.0.so.0)
                #5  0x00007f61cce3c08c start_thread (libpthread.so.0)
                #6  0x00007f61ccb73e7f __clone (libc.so.6)
```

**Comment by tidux** [comment]
```
gdb) bt
#0  0x00007fc6f7b195c7 in gtk_widget_get_toplevel () at /usr/lib/libgtk-3.so.0
#1  0x00007fc6f7b3b593 in  () at /usr/lib/libgtk-3.so.0
#2  0x00007fc6f7b3b903 in gtk_window_group_add_window () at /usr/lib/libgtk-3.so.0
#3  0x00007fc6f7b38378 in gtk_window_set_transient_for () at /usr/lib/libgtk-3.so.0
#4  0x00007fc6f7ad0793 in  () at /usr/lib/libgtk-3.so.0
#5  0x00007fc6f7ad1678 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007fc6f79bfcfe in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#7  0x00007fc6f74c89f6 in  () at /usr/lib/libgdk-3.so.0
#8  0x00007fc6f74fb225 in  () at /usr/lib/libgdk-3.so.0
#9  0x00007ffdd11c7700 in  ()
#10 0x000055d6298bb800 in  ()
#11 0x0000000000000000 in  ()
```

**Comment by vaurelios** [comment]
Here too, Arch too.

**Comment by Omar-Elrefaei** [comment]
This also happens to me in both Ubuntu 17.04 and 17.10

**Comment by elcste** [comment]
Reported on Launchpad for Ubuntu MATE: https://bugs.launchpad.net/ubuntu-mate/+bug/1771890

**Comment by icycle77** [comment]
Hit this today on Mate 1.22.0, the current version in the latest Linux Mint 19.3.

Steps to repro, crashes every time:
* Edit -> Keyboard Shortcuts
* double click on one shortcut, enter a new key combo
* double click on another shortcut, terminal crashes

Also just saw another crash, no idea what happened but 1 window with 3 tabs was no longer.

Planning to switch terminals now.

**Comment by ericek111** [comment]
Still an issue. 
```
#0  0x00007ffff78be71e in gtk_widget_get_toplevel () from /usr/lib/libgtk-3.so.0
#1  0x00007ffff7984354 in ?? () from /usr/lib/libgtk-3.so.0
#2  0x00007ffff78e020c in gtk_window_group_add_window () from /usr/lib/libgtk-3.so.0
#3  0x00007ffff78cfbd8 in gtk_window_set_transient_for () from /usr/lib/libgtk-3.so.0
#4  0x00007ffff7879655 in ?? () from /usr/lib/libgtk-3.so.0
#5  0x00007ffff787a103 in ?? () from /usr/lib/libgtk-3.so.0
#6  0x00007ffff7763669 in gtk_main_do_event () from /usr/lib/libgtk-3.so.0
#7  0x00007ffff74adb77 in ?? () from /usr/lib/libgdk-3.so.0
#8  0x00007ffff7506438 in ?? () from /usr/lib/libgdk-3.so.0
#9  0x00007ffff6e70199 in ?? () from /usr/lib/libglib-2.0.so.0
#10 0x00007ffff6ecf3bf in ?? () from /usr/lib/libglib-2.0.so.0
#11 0x00007ffff6e70dc7 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#12 0x00007ffff77612bf in gtk_main () from /usr/lib/libgtk-3.so.0
#13 0x000055555557089d in main ()
```

**Comment by bloovis** [comment]
Hit this on Linux Mint 22.2 Mate.  Edit Keyboard Shortcuts, attempt to disable Full Screen (mapped to F11 by default) using Backspace when prompted for new shortcut.

Package: mate-terminal                   
Version: 1.26.1+mint1
